-- Test-specific data for integration tests
-- BCrypt hash for "test123" (generated by application's PasswordEncoder)

-- Add test users with proper BCrypt passwords
-- Using explicit user_id values starting from 1000 to avoid conflicts with existing data
INSERT INTO users (user_id, first_name, last_name, email, phone, password_hash, role, status, branch_id) VALUES
(1000, 'Test', 'Staff', 'staff@test.com', '617-555-TEST1', '$2a$10$p8VI5TWq/Z2tVeh4tXt.HON.lU5L1/qjC.TXGPo2GJxctbKxkuJaK', 0, 1, 1),
(1001, 'Test', 'Staff2', 'staff2@test.com', '617-555-TEST2', '$2a$10$p8VI5TWq/Z2tVeh4tXt.HON.lU5L1/qjC.TXGPo2GJxctbKxkuJaK', 0, 1, 2),
(1002, 'Test', 'Volunteer', 'volunteer@test.com', '617-555-TEST3', '$2a$10$p8VI5TWq/Z2tVeh4tXt.HON.lU5L1/qjC.TXGPo2GJxctbKxkuJaK', 1, 1, 1),
(1003, 'Test', 'Volunteer2', 'volunteer2@test.com', '617-555-TEST4', '$2a$10$p8VI5TWq/Z2tVeh4tXt.HON.lU5L1/qjC.TXGPo2GJxctbKxkuJaK', 1, 1, 2),
(1004, 'Inactive', 'User', 'inactive@test.com', '617-555-TEST5', '$2a$10$p8VI5TWq/Z2tVeh4tXt.HON.lU5L1/qjC.TXGPo2GJxctbKxkuJaK', 0, 0, 1);

-- Add corresponding staff records
INSERT INTO staff (user_id, job_title, hire_date) VALUES
(1000, 'Test Manager', NOW()),
(1001, 'Test Coordinator', NOW()),
(1004, 'Former Manager', DATE_SUB(NOW(), INTERVAL 1 YEAR));

-- Add corresponding volunteer records
INSERT INTO volunteers (user_id, availability, background_check) VALUES
(1002, 'Weekends', 1),
(1003, 'Weekdays', 1);

-- Add test-specific food items to avoid conflicts with seed data
INSERT INTO food_items (sku, food_name, food_description, storage_condition, category_id) VALUES
('TEST-001', 'Test Canned Beans', 'Test item for donation tests', 'Room temperature', 2),
('TEST-002', 'Test Fresh Apples', 'Test item for donation tests', 'Refrigerated', 1),
('TEST-003', 'Test Milk', 'Test item for distribution tests', 'Refrigerated', 2),
('TEST-004', 'Test Chicken', 'Test item for smoke test', 'Frozen', 2);
